ti-mcu-plus-sdk: build with sysroot TI tools
The MCU+ SDK demo build inherits host-path defaults from imports.mak,
which point to $(HOME)/ti on Linux. In clean Yocto builds this causes
missing tool errors (sysconfig/node and tiarmclang).

For example:

| make: Leaving directory '/workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/git/examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-var-som/m4fss0-0_freertos/ti-arm-clang'
| NOTE: make -j 32 -C examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-var-som/m4fss0-0_freertos/ti-arm-clang
| make: Entering directory '/workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/git/examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-var-som/m4fss0-0_freertos/ti-arm-clang'
| Generating SysConfig files ...
| /home/vari/ti/sysconfig_1.23.0/nodejs/node /home/vari/ti/sysconfig_1.23.0/dist/cli.js --product /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/git/.metadata/product.json --device AM62x --context m4fss0-0 --part Default --package ALW --output generated/ ../example.syscfg
| make: /home/vari/ti/sysconfig_1.23.0/nodejs/node: No such file or directory
| make: *** [makefile:227: syscfg] Error 127
| make: Leaving directory '/workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/git/examples/drivers/ipc/ipc_rpmsg_echo_linux/am62x-var-som/m4fss0-0_freertos/ti-arm-clang'
| ERROR: oe_runmake failed
| WARNING: /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/run.do_compile.52467:171 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
| 	#1: bbfatal_log, /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/run.do_compile.52467, line 171
| 	#2: die, /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/run.do_compile.52467, line 155
| 	#3: oe_runmake, /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/run.do_compile.52467, line 150
| 	#4: do_compile, /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/run.do_compile.52467, line 144
| 	#5: main, /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/run.do_compile.52467, line 184

Summary: 1 task failed:
  /workdir/sources/meta-variscite-bsp-ti/recipes-ti/ti-mcu-plus-sdk/ti-mcu-plus-sdk_11.00.00.16.bb:do_compile
    log: /workdir/build/arago-tmp-default-glibc/work/aarch64-oe-linux/ti-mcu-plus-sdk/11.00.00.16/temp/log.do_compile.52467
Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
Error: Command failed with exit status 1

Problematic upstream defaults:
- https://github.com/varigit/ti-mcu-plus-sdk/blob/6790cf5d3c752afb5e02e88248e74cf09ebd0270/imports.mak#L31
- https://github.com/varigit/ti-mcu-plus-sdk/blob/6790cf5d3c752afb5e02e88248e74cf09ebd0270/imports.mak#L53
- https://github.com/varigit/ti-mcu-plus-sdk/blob/6790cf5d3c752afb5e02e88248e74cf09ebd0270/imports.mak#L55
- https://github.com/varigit/ti-mcu-plus-sdk/blob/6790cf5d3c752afb5e02e88248e74cf09ebd0270/imports.mak#L50

This patch fixes it by adding `sysconfig` to `DEPENDS` and passing `TOOLS_PATH`, `SYSCFG_PATH`, and `CGT_TI_ARM_CLANG_PATH` from `RECIPE_SYSROOT_NATIVE` into `oe_runmake`. This removes host `$(HOME)/ti` assumptions and makes tool resolution reproducible in clean Yocto builds.

Signed-off-by: Nate Drude <nate.d@variscite.com>